# Generated by Django 5.2 on 2025-05-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_item'),
        ('shop', '0004_remove_item_available_remove_item_description_and_more'),
    ]

    operations = [
    ]
