# Generated by Django 5.2 on 2025-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_loyaltyprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
