# Generated by Django 5.2 on 2025-05-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_item_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='offer_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
