# Generated by Django 5.2 on 2025-05-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_has_offer_item_offer_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy_two_get_one',
            field=models.BooleanField(default=False),
        ),
    ]
